// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.wedding.domain;

import com.wedding.domain.Rsvp;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Rsvp_Roo_Configurable {
    
    declare @type: Rsvp: @Configurable;
    
}
